on:
  workflow_dispatch:
    inputs:
      sha:
        description: commit sha
        required: true

name: Release Development
jobs:
  release-dev:
    name: release dev ${{ github.event.inputs.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm run build
      - name: set and echo dev version
        run: |
          npm_command="npm version --commit-hooks false --git-tag-version false"
          version_string=`$npm_command prerelease --preid "dev"`
          short_sha=`git rev-parse --short HEAD`
          dev_version=`echo -n $version_string | sed "s/.$/${short_sha}/"`
          $npm_command $dev_version
          echo "DEV_VERSION=$dev_version" >> $GITHUB_ENV
      - run: npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: echo jsdelivr link
        run: echo "https://cdn.jsdelivr.net/npm/${{ vars.NPM_PACKAGE }}@${{ env.DEV_VERSION }}/"
